
kind: Deployment
apiVersion: apps/v1
metadata:
  name: languagetool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: languagetool
  template:
    metadata:
      labels:
        app: languagetool
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: Java_Xms
            value: "1g"
          - name: Java_Xmx
            value: "1g"
        name: languagetool
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: languagetool-ngrams
          mountPath: /ngrams
        ports:
          - name: http
            containerPort: 8010
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 200
          timeoutSeconds: 2
          periodSeconds: 11
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 9
          successThreshold: 1
          failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: languagetool-ngrams
        persistentVolumeClaim:
          claimName: languagetool-ngrams

